<?php

namespace ContainerJt7ErZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DVWcmHMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DVWcmHM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DVWcmHM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'membre' => ['privates', '.errored..service_locator.DVWcmHM.App\\Entity\\Membre', NULL, 'Cannot autowire service ".service_locator.DVWcmHM": it needs an instance of "App\\Entity\\Membre" but this type has been excluded in "config/services.yaml".'],
        ], [
            'membre' => 'App\\Entity\\Membre',
        ]);
    }
}
