<?php

namespace ContainerJt7ErZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DOZ5WekService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DOZ5Wek' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DOZ5Wek'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandePressing' => ['privates', '.errored..service_locator.DOZ5Wek.App\\Entity\\DemandePressing', NULL, 'Cannot autowire service ".service_locator.DOZ5Wek": it needs an instance of "App\\Entity\\DemandePressing" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demandePressing' => 'App\\Entity\\DemandePressing',
            'entityManager' => '?',
        ]);
    }
}
