<?php

namespace ContainerJt7ErZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2e4vPGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u2e4vPG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u2e4vPG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'membreRepository' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'pressingRepository' => ['privates', 'App\\Repository\\PressingRepository', 'getPressingRepositoryService', true],
            'resetPasswordHelper' => ['privates', 'symfonycasts.reset_password.helper', 'getSymfonycasts_ResetPassword_HelperService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'membreRepository' => 'App\\Repository\\MembreRepository',
            'passwordHasher' => '?',
            'pressingRepository' => 'App\\Repository\\PressingRepository',
            'resetPasswordHelper' => '?',
        ]);
    }
}
