<?php

namespace ContainerJt7ErZz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandePressingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DOZ5Wek.App\Entity\DemandePressing' shared service.
     *
     * @return \App\Entity\DemandePressing
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DOZ5Wek": it needs an instance of "App\\Entity\\DemandePressing" but this type has been excluded in "config/services.yaml".');
    }
}
