<?php

namespace ContainerIdfUhxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OeyruIAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OeyruIA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OeyruIA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeRepository' => ['privates', 'App\\Repository\\EmployeRepository', 'getEmployeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'resetPasswordHelper' => ['privates', 'symfonycasts.reset_password.helper', 'getSymfonycasts_ResetPassword_HelperService', true],
        ], [
            'employeRepository' => 'App\\Repository\\EmployeRepository',
            'entityManager' => '?',
            'mailer' => '?',
            'resetPasswordHelper' => '?',
        ]);
    }
}
