<?php

namespace ContainerIdfUhxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4aMbDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4aMbD_T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4aMbD_T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articlesRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'commandeDetailRepository' => ['privates', 'App\\Repository\\CommandeDetailRepository', 'getCommandeDetailRepositoryService', true],
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'articlesRepository' => 'App\\Repository\\ArticlesRepository',
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'commandeDetailRepository' => 'App\\Repository\\CommandeDetailRepository',
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
        ]);
    }
}
