<?php

namespace ContainerIdfUhxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVQXJQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QVQX_jQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QVQX_jQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandePressingRepository' => ['privates', 'App\\Repository\\DemandePressingRepository', 'getDemandePressingRepositoryService', true],
        ], [
            'demandePressingRepository' => 'App\\Repository\\DemandePressingRepository',
        ]);
    }
}
