<?php

namespace ContainerIdfUhxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VPpFEGGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VPpFEGG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VPpFEGG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandePressing' => ['privates', '.errored..service_locator.VPpFEGG.App\\Entity\\DemandePressing', NULL, 'Cannot autowire service ".service_locator.VPpFEGG": it needs an instance of "App\\Entity\\DemandePressing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'demandePressing' => 'App\\Entity\\DemandePressing',
        ]);
    }
}
