<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pressing extends \App\Entity\Pressing implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null],
        "\0".parent::class."\0".'commandeDetails' => [parent::class, 'commandeDetails', null],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'demandePressing' => [parent::class, 'demandePressing', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'employes' => [parent::class, 'employes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'membre' => [parent::class, 'membre', null],
        "\0".parent::class."\0".'membres' => [parent::class, 'membres', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'paiements' => [parent::class, 'paiements', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'adresse' => [parent::class, 'adresse', null],
        'articles' => [parent::class, 'articles', null],
        'client' => [parent::class, 'client', null],
        'commandeDetails' => [parent::class, 'commandeDetails', null],
        'commandes' => [parent::class, 'commandes', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'demandePressing' => [parent::class, 'demandePressing', null],
        'email' => [parent::class, 'email', null],
        'employes' => [parent::class, 'employes', null],
        'id' => [parent::class, 'id', null],
        'membre' => [parent::class, 'membre', null],
        'membres' => [parent::class, 'membres', null],
        'nom' => [parent::class, 'nom', null],
        'paiements' => [parent::class, 'paiements', null],
        'telephone' => [parent::class, 'telephone', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
