<?php

namespace Container6ylLxqp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Slx5PYUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.slx5PYU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.slx5PYU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pressing' => ['privates', '.errored..service_locator.slx5PYU.App\\Entity\\Pressing', NULL, 'Cannot autowire service ".service_locator.slx5PYU": it needs an instance of "App\\Entity\\Pressing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'pressing' => 'App\\Entity\\Pressing',
        ]);
    }
}
