<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIdfUhxP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIdfUhxP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIdfUhxP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIdfUhxP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIdfUhxP\App_KernelDevDebugContainer([
    'container.build_hash' => 'IdfUhxP',
    'container.build_id' => '501d4ddb',
    'container.build_time' => 1745413471,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIdfUhxP');
