<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27smIkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27smIkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container27smIkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container27smIkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container27smIkx\App_KernelDevDebugContainer([
    'container.build_hash' => '27smIkx',
    'container.build_id' => 'c37a8e74',
    'container.build_time' => 1745509328,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container27smIkx');
