<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaXr8Ye\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaXr8Ye/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaXr8Ye.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaXr8Ye\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaXr8Ye\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaXr8Ye',
    'container.build_id' => 'c947e51e',
    'container.build_time' => 1746494685,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaXr8Ye');
