<?php

namespace ContainerW8WvUNn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RAnmtaZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RAnmtaZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RAnmtaZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.RAnmtaZ.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.RAnmtaZ": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
        ]);
    }
}
