<?php

namespace ContainerW8WvUNn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPressingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.slx5PYU.App\Entity\Pressing' shared service.
     *
     * @return \App\Entity\Pressing
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.slx5PYU": it needs an instance of "App\\Entity\\Pressing" but this type has been excluded in "config/services.yaml".');
    }
}
